* About

This is a guide to do all the things described in Roger Skyline 1. This might not take so much time, or let me say it otherwise, *I DON'T HAVE MUCH TIME! I NEED TO GET OUT OF THE BLACK HOLE AS SOON AS POSSIBLE!*

* A Debian VM

For the moment, All of this is done on a =24-inch iMac (Late 2006)= running a Max OS X =Lion 10.7.5= using a =Debian 9.9= in =VirtualBox 4.3=

Here's a link to [[https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.0.0-amd64-netinst.iso][Debian 10.10 Net Install]] for latest packages + minimum download/install time. Also [[https://download.virtualbox.org/virtualbox/6.0.10/VirtualBox-6.0.10-132072-OSX.dmg][VirtualBox 6.0]]. Important thing is to allocate exactly =8 GB= with no partitioning!

* IN-PROGRESS Network and Security

- State "IN-PROGRESS"                  [2019-08-01 Thu 14:23]

** Initial Configuration

+ create a new non-root user using =adduser <NAME>=
+ update the system using =apt-get update -y && apt-get upgrade -y=
+ install essential tools using =apt-get install -y sudo vim apache2 portsentry ufw fail2ban mailutils net-tools=
  + sudo :: execute commands as =root=
  + vim :: the perfect text editor for servers, since their non GUI systems, mostly
  + fail2ban :: monitor server logs and detects any IP with a suspesious activity, after predefined number of failure, it blocks the IP for a specific duration[fn:1]
  + portsentry :: port scanning utility, good for scanning port and avoiding attacks[fn:2]
  + apache2 :: the fucking HTTP server itself[fn:3]
  + mailutils :: the swiss army knife of electronic mail handling[fn:4]
  + ufw :: uncomplicated firewall[fn:5]

** Configure Sudo

Using =vim= as =root=, add the /user's previlege specification/ the file =/etc/sudoers=. Right at the comment =# User privilege specification= add =<LOGIN>    ALL=(ALL:ALL) NOPASSWD:ALL=

** Configure static IP

#+BEGIN_QUOTE
/Must change the network adapter from NAT to Bridged Adapter in the VM's settings/
#+END_QUOTE

We need to setup the /primary network/, thus we need to edit =/etc/network/interfaces=. We find that the primary network (for my VM at least) is =enp0s3=, found under the line =#The primary network interface=.

To configure a static IP we need to create the file[fn:6] =/etc/network/interfaces.d/enp0s3=.

#+BEGIN_SRC
iface enp0s3 inet static
        address 10.11.200.247
        netmask 255.255.255.252
        gateway 10.11.254.254
#+END_SRC

Finally, we restart the network using =sudo service networking restart= and check that using =ip addr= and look for =enp0s3=

** IN-PROGRESS Configure SSH

- State "IN-PROGRESS" from              [2019-08-01 Thu 14:19]

#+BEGIN_QUOTE
/Some info about ssh in general/
#+END_QUOTE

*** Configure default port

SSH could be configured by editing the default port (22) in the file =/etc/ssh/sshd_config=, The port should not be chosen arbitrary (or it might be so. but, it *must not be already used* as it would create conflicts). We can check that using =sudo lsof -i -P -n | grep LISTEN | grep <PORT>=.

However, IANA -- The Internet Assigned Numbers Authority (IANA) is responsible for the global coordination of the DNS Root, IP addressing, and other Internet protocol resources. their port assignment guidelines said the following:

#+BEGIN_QUOTE
/port numbers are divided into three ranges: Well Known Ports, Registered Ports, and Dynamic and/or Private Ports./

- The Well Known Ports are those from =0= through =1023= and SHOULD NOT be used.
- Registered Ports are those from =1024= through =49151= should also be avoided too.
- Dynamic and/or Private Ports are those from 49152 through 65535 and can be used.

Though nothing is stopping you from using reserved port numbers, our suggestion may help avoid technical issues with port allocation in the future.
#+END_QUOTE

However, I have chosen =1412= since it's my nickname anyway, =0x0584=

*** Setup public keys

** TODO Configure Firewall

** TODO Configure ports

** TODO Manage Services and Packages

* PENDING Web Deployment

- State "PENDING"                     [2019-08-01 Thu 14:23]

* Footnotes

[fn:6] it's possible to change it at place but it's not recommended. this is a [[https://linuxconfig.org/how-to-setup-a-static-ip-address-on-debian-linux][good article]]

[fn:5] this seems like a good [[https://www.digitalocean.com/community/tutorials/how-to-setup-a-firewall-with-ufw-on-an-ubuntu-and-debian-cloud-server][documentation]]

[fn:4] good luck reading any GNU [[https://mailutils.org/manual/mailutils.html][documentation]]

[fn:3] [[https://www.hostinger.com/tutorials/what-is-apache][good article]] comparison between many web servers including NGINX and TOMCAT

[fn:2] this [[https://wiki.debian-fr.xyz/Portsentry][debian blog]] has a some good documentation. also [[https://www.symantec.com/connect/articles/portsentry-attack-detection-part-one][here]]!

[fn:1] here's a [[https://www.linode.com/docs/security/using-fail2ban-for-security/][good place]] to document about fail2ban for serve, and [[https://www.digitalocean.com/community/tutorials/how-to-protect-ssh-with-fail2ban-on-ubuntu-14-04][this]] one is to secure SSH
