* About

This is a guide to do all the things described in Roger Skyline 1. This might not take so much time, or let me say it otherwise, *I DON'T HAVE MUCH TIME! I NEED TO GET OUT OF THE BLACK HOLE AS SOON AS POSSIBLE!*

* A Debian VM

For the moment, All of this is done on a =24-inch iMac (Late 2006)= running a Max OS X =Lion 10.7.5= using a =Debian 9.9= in =VirtualBox 4.3=

Here's a link to [[https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.0.0-amd64-netinst.iso][Debian 10.10 Net Install]] for latest packages + minimum download/install time. Also [[https://download.virtualbox.org/virtualbox/6.0.10/VirtualBox-6.0.10-132072-OSX.dmg][VirtualBox 6.0]]. Important thing is to allocate exactly =8 GB= with no partitioning!

* Network and Security

** Initial Configuration

+ create a new non-root user using =adduser <NAME>=
+ update the system using =apt-get update -y && apt-get upgrade -y=
+ install essential tools using =apt-get install -y sudo vim apache2 portsentry ufw fail2ban mailutils=
  + sudo :: execute commands as =root=
  + vim :: the perfect text editor for servers, since their non GUI systems, mostly
  + fail2ban :: monitor server logs and detects any IP with a suspesious activity, after predefined number of failure, it blocks the IP for a specific duration [fn:1]
  + portsentry :: port scanning utility, good for scanning port and avoiding attacks [fn:2]
  + apache2 :: the fucking HTTP server itself [fn:3]
  + mailutils :: the swiss army knife of electronic mail handling [fn:4]
  + ufw :: uncomplicated firewall [fn:5]

** Configure Sudo

Using =vim= as =root=, add the /user's previlege specification/ the file =/etc/sudoers=. Right at the comment =# User privilege specification= add =<LOGIN>    ALL=(ALL:ALL) NOPASSWD:ALL=

** Configure static IP



* Footnotes

[fn:5] this seems like a good [[https://www.digitalocean.com/community/tutorials/how-to-setup-a-firewall-with-ufw-on-an-ubuntu-and-debian-cloud-server][documentation]]

[fn:4] good luck reading any GNU [[https://mailutils.org/manual/mailutils.html][documentation]]

[fn:3] [[https://www.hostinger.com/tutorials/what-is-apache][good article]] comparison between many web servers including NGINX and TOMCAT

[fn:2] this [[https://wiki.debian-fr.xyz/Portsentry][debian blog]] has a some good documentation. also [[https://www.symantec.com/connect/articles/portsentry-attack-detection-part-one][here]]!

[fn:1] here's a [[https://www.linode.com/docs/security/using-fail2ban-for-security/][good place]] to document about fail2ban for serve, and [[https://www.digitalocean.com/community/tutorials/how-to-protect-ssh-with-fail2ban-on-ubuntu-14-04][this]] one is to secure SSH
